[package]
name = "api"
version = "0.1.0"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
by-axum.workspace = true
by-types.workspace = true
serde = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["json"] }
tokio = { version = "1.43.0", features = ["full"] }
tracing.workspace = true
sqlx = { version = "0.8.3", features = [
    "sqlite",
    "postgres",
    "runtime-tokio",
    "time",
    "bigdecimal",
] }

models = { workspace = true, features = ["server"] }
chrono = "0.4.40"
[features]
default = []
server = []
lambda = ["by-axum/lambda"]
