[package]
name = "main-ui"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
dioxus = { workspace = true, features = ["default", "router", "fullstack"] }
dioxus-logger.workspace = true
by-components.workspace = true
dioxus-translate.workspace = true
dioxus-aws.workspace = true
by-types.workspace = true


wasm-bindgen = { version = "0.2.100" }
wasm-bindgen-futures = { version = "0.4.49" }
web-sys = { version = "0.3.74" }
reqwest = { workspace = true, features = ["json", "blocking"] }
serde = { workspace = true, features = ["derive"] }

#FIXME: `rest-api` crate has `getrandom` dependency, but it's listed here
getrandom = { version = "0.2", features = ["js"] }


[features]
default = []
server = ["dioxus-aws/server"]
lambda = ["dioxus-aws/lambda", "server"]
web = ["dioxus-aws/web", "dioxus-translate/web"]
